# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'enpal_assessment_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'enpal_assessment_project'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "logs"
  - "target"
  - "dbt_packages"
  - "dbt_internal_packages"

# Configuring models
models:
  enpal_assessment_project:
    +schema: pipedrive_analytics

    staging:
      +materialized: view

    intermediate:
      +materialized: incremental
      +incremental_strategy: delete+insert

    marts:
      +materialized: table
